name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: downloading the resource code  
        uses: actions/checkout@v2
      - name: npm install, build and test
        run: |
         npm install
         npm run build --if-present
         npm test  
 
      
