name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: downloading the resource code  
        uses: actions/checkout@v2
      - name: installing the dependency
        run: npm install
      - name: testing the code
        run: npm run test
      - name: building the app
        run: npm run build

